### ISSUE TITLE
Consider using "Serial Test" to limit test threads?

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/cli-old#119]

**Comment by smklein** [comment]
I saw the comment in the README about running with a single test thread - in Omicron, I used https://docs.rs/serial_test/latest/serial_test/index.html when I need this behavior, and it worked pretty well. This allows the tests which *can* be run concurrently to remain that way, and avoids the needs for special arguments to `cargo test`.

**Comment by jessfraz** [comment]
sadly I have forgotten which are and aren't so it will take a bit more context to do now but thanks for the tip, I'll go back through when I get a chance
