### ISSUE TITLE
Mac install has `sha256sum` prereq

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/cli-old#125]
I had to `brew install coreutils` to get `sha256sum`.

**Comment by jessfraz** [comment]
well you could not check the sha sum but yes you are right, this will be easier when we have homebrew integration ;)

**Comment by jessfraz** [comment]
cc #25

**Comment by jessfraz** [comment]
added a note to the releases 8dae4356bbde5689b47a3ef4d85397cb91d88ca8
