### ISSUE TITLE
"warning: 'default' is not a known configuration key" when following suggestion to set a default host

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/cli-old#137]
Repro steps:

- Use `oxide auth login` to log in to two different hosts
- Run `oxide org list`; observe `No host has been set as default. Try setting a default with oxide config set -H <host> default true. Options for hosts are: <host list>`
- Run `oxide config set -H <some host> default true`

Expected: the supplied host becomes the default & subsequent commands target it

Observed: `! warning: 'default' is not a known configuration key`; `oxide org list` continues to fail. If I manually add `default = true` to the appropriate entry in $HOME/.config/hosts.toml, everything begins to work.

From an extremely quick skim of the code it looks to me like this might just be a missing option in `config_options()` in config.rs.

**Comment by karencfv** [comment]
Closing this as it is no longer an issue since we've moved on to https://github.com/oxidecomputer/oxide-sdk-and-cli
