### ISSUE TITLE
Would like a `--force` flag for some operations

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/cli-old#179]
Currently, operations like `oxide instance stop` bring up a prompt, requiring the user to type in the name of the instance to be stopped. That's a nice default, but it would also be great to have a flag like `--force` or `--assume-yes` or similar that bypasses the check and directly runs the operation.

**Comment by bnaecker** [comment]
It seems there's a [confirm argument](https://github.com/oxidecomputer/cli/blob/e889457a1cdc24501a8221b018cae6e9d43c4d89/cli-macro-impl/src/lib.rs#L1922), but it appears that's only for `instance delete`.

**Comment by karencfv** [comment]
This feature will be really useful, especially for when the CLI is used within scripts :)

At the moment we're fixing several things within the CLI, so I can't promise that this feature will be ready soon. Definitely something to have in the backlog though!

**Comment by bnaecker** [comment]
The `--confirm` flag appears to be present in `e889457a1cdc24501a8221b018cae6e9d43c4d89`. Not sure if that's new, but that definitely satisfies my use case. @karencfv Feel free to close, unless there are other places you'd like to add this.

**Comment by karencfv** [comment]
Thanks @bnaecker! I see all delete commands have a `--confirm` flag.

I'd like to leave this open for now. It might be worth it to consider changing the flag from `--confirm` to `--force` if that change will make its functionality clearer.

**Comment by karencfv** [comment]
This is already implemented in new CLI rework
