### ISSUE TITLE
[BUG] Error when creating blank disk because block size is not specified

### ISSUE THREAD

**Issue by ryaeng** [oxidecomputer/cli-old#187]
See screenshot below.
=
<img width="689" alt="Screen Shot 2022-06-09 at 5 40 55 PM" src="https://user-images.githubusercontent.com/17517466/172950216-dcd2100d-0a02-4810-9889-0c74d102639a.png">

**Comment by ryaeng** [comment]
I've poked around on this one for a couple of hours. Couldn't figure out how to add block size prompt.

@jessfraz Could you point me in the right direction?

**Comment by jessfraz** [comment]
likely in the SDK oxide.rs seems like it cant parse the JSON

**Comment by jessfraz** [comment]
you can add a unit test there for what you are doing and make sure it actually is valid json

**Comment by karencfv** [comment]
Heya @ryaeng I just merged the fix for this issue a couple days ago https://github.com/oxidecomputer/cli/pull/182 :) 

Could you confirm if you're building the CLI from the latest commit?

**Comment by ryaeng** [comment]
> Heya @ryaeng I just merged the fix for this issue a couple days ago #182 :)
> 
> Could you confirm if you're building the CLI from the latest commit?

Lemme try again.

**Comment by ryaeng** [comment]
Okay. It's working via #182. 

The issue I would propose is labeling the block size as blank value. That is not intuitive by design. Should we change that behavior?

**Comment by karencfv** [comment]
Heya @ryaeng sorry for the late reply! Thanks for the feedback :) and yes I agree, we should change that behaviour. Since this issue is a bug report I've opened https://github.com/oxidecomputer/cli/issues/216 to follow along for that feature enhancement.

I'll close this issue unless there is something else needed for the original bug report?
