### ISSUE TITLE
`oxide image global list` requires `project` and `organization` but doesn't need it

### ISSUE THREAD

**Issue by just-be-dev** [oxidecomputer/cli-old#194]
`oxide image global list` maps to the [global images route](https://github.com/oxidecomputer/omicron/blob/7020b0fce1b9c269d5ce08c645a9883818fd773b/openapi/nexus.json#L213) which is at the root and doesn't require `project` or `organization` to be provided.

**Comment by karencfv** [comment]
This is fixed with new API/CLI rework
