### ISSUE TITLE
"cargo build --test" causing OOM on stable toolchain

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/cli-old#205]
Why? I dunno. But I'm flipping the toolchain to nightly in the meantime, and filing this issue as reference.

**Comment by smklein** [comment]
This was repro'd on `rustc 1.61.0 (fe5b13d68 2022-05-18)`

**Comment by karencfv** [comment]
No longer an issue with https://github.com/oxidecomputer/oxide-sdk-and-cli
