### ISSUE TITLE
Improve prompt for disk create prompt

### ISSUE THREAD

**Issue by karencfv** [oxidecomputer/cli-old#216]
When creating a disk using the prompt, it is not clear what the value should be for a "blank disk". It would be more intuitive to ask for "block size".

**Comment by ryaeng** [comment]
@karencfv I can take a look at this one.

**Comment by karencfv** [comment]
🙇‍♀️

**Comment by ryaeng** [comment]
My research has led me [here](https://github.com/oxidecomputer/cli/blob/4ecf531a262d8cbc36b34e3ec6f8ea36013ecf40/cli-macro-impl/src/lib.rs#L1268). After entering blank or the disk type, how are the subsequent prompts being generated?

**Comment by karencfv** [comment]
Hey, sorry about the rabbit hole 😓 . It looks like there's a prompt extension file and the changes need to be done here -> https://github.com/oxidecomputer/cli/blob/main/src/prompt_ext.rs#L154-L191

Just as a heads up, I'm working on migrating the rust SDK to use progenitor as the client generator, and changing the way commands are generated in the CLI as well, so some of these things will change :)

**Comment by karencfv** [comment]
This is fixed with new CLI rework
