### ISSUE TITLE
want support for updating IAM policy

### ISSUE THREAD

**Issue by davepacheco** [oxidecomputer/cli-old#221]
Stuff like adding a role assignment for a user to a resource:

```
$ echo '{"role_assignments": [ {"identity_type": "silo_user", "identity_id": "1991c8f1-5293-40a7-8933-2be7b81e1994", "role_name": "collaborator" }]}' | oxide api --input - -X PUT /silos/pluto/policy
{
  "role_assignments": [
    {
      "identity_id": "489025d3-0f85-4ef9-b4b0-fc7ce887be7e",
      "identity_type": "silo_user",
      "role_name": "collaborator"
    }
  ]
}
```

Let me know if I can help with the API part or semantics.

**Comment by karencfv** [comment]
Thanks! Same as https://github.com/oxidecomputer/cli/issues/219#issuecomment-1173219007 for this one

**Comment by davepacheco** [comment]
Same as what I said there: These are one-time steps that are more akin to rack setup than the rest of the demo.  So while we do plan to demo features that use this, it's probably okay to use the raw API commands since it'll be happening offline before the actual demo starts.  CC @smklein -- for this one in particular, I imagine we'll want to make sure we sequence the script to not need this _during_ the demo.

**Comment by karencfv** [comment]
🙇‍♀️ thanks!

**Comment by karencfv** [comment]
This is being worked on as part of a larger task in https://github.com/oxidecomputer/oxide-sdk-and-cli
