### ISSUE TITLE
Unhelpful unwrap and error message when adding SSH key

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/cli-old#222]
I'm trying to add an SSH key through the CLI and hit an `unwrap()` with an unhelpful error message.

```
bnaecker@feldspar : ~/omicron $ ../cli/target/release/oxide ssh-key add
Your SSH key is: Ed25519(Ed25519KeyPair { public_key: PublicKey("5867baf93bfc3271fd2353918c14a9f6aa8ea4590f45c2a867016fe2d8038d6e") })
Your SSH public key is: PublicKey { key_type: KeyType { name: "ssh-ed25519", short_name: "ED25519", is_cert: false, is_sk: false, kind: Ed25519, plain: "ssh-ed25519" }, kind: Ed25519(Ed25519PublicKey { key: [88, 103, 186, 249, 59, 252, 50, 113, 253, 35, 83, 145, 140, 20, 169, 246, 170, 142, 164, 89, 15, 69, 194, 168, 103, 1, 111, 226, 216, 3, 141, 110], sk_application: None }), comment: None }
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', src/main.rs:201:78
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Looking at the source I have, which is at commit `5f58d141a61de2347a1837d2c2db2f71453dba2a`, so a bit behind the current main, it's hitting [this unwrap](https://github.com/oxidecomputer/cli/blob/f8db200c4c3e2c16b64eb4c7bc6615165e5a454f/src/main.rs#L210). To be clear, this looks unrelated to SSH keys specifically, that's just the command I happened to run when I hit this.

I'm not entirely sure what file was not found, since running again with `RUST_BACKTRACE=1` didn't fail. But, looking at the `handle_update` method, I think I see the problem. It first checks if the CLI was installed via Homebrew. That works by running `brew --prefix` to check for the location Homebrew's Cellar. But if you're not running on macOS, or if you don't have Homebrew installed, that subprocess will fail. There's no handling of that error, meaning that the `std::io::Result` will be bubbled up to `handle_udpate`, which just `unwraps()` it. The code should be changed so that a lack of Homebrew returns `false` from `is_under_homebrew()`.

**Comment by plotnick** [comment]
Fixed with #223.
