### ISSUE TITLE
Unhelpful unwrap looking for configuration file

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/cli-old#225]
I hit an unhelpful unwrap an error message on [this line](https://github.com/oxidecomputer/cli/blob/6a2301681b812f35ff3003027b9ffbe61bb25956/src/main.rs#L201). I've not debugged in depth, but it appears to be looking for a configuration file at some set of hard-coded paths, and failing if those don't exist. It should probably gracefully handle those directories or files not existing (since they appear to be a cross-platform config-file location thing). I'll fill in more details as I get them.

**Comment by karencfv** [comment]
Closing this as it is no longer an issue since we've moved on to https://github.com/oxidecomputer/oxide-sdk-and-cli
