### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by karencfv** [oxidecomputer/cli-old#229]
~More often than not, as an SRE, it’s necessary to toggle between human readable and json output often. Generally this can be set through a global flag, which makes it very easy to switch from one output format to another. With our CLI this has to be set through another command  `$ oxide config set format json`. Generally we want to give our users less commands to have to remember, and less steps to get their work done.~

~There should be a global `--json` flag~

Currently there is a `--format` flag in most commands which accepts different values. From the description it's not very clear as to what those values should be `-f, --format <FORMAT> Output format`.

This flag should be global and the description should say what values are accepted and what they do.

**Comment by plotnick** [comment]
Most commands accept a `--format` option, whose value can be one of `json`, `yaml`, or `table`. Is this different than what you're suggesting here?

**Comment by karencfv** [comment]
ha! Thanks @plotnick 😄  hadn't even realised that flag was there. I'll change the issue to say the flag needs a better description

**Comment by ryaeng** [comment]
@karencfv I can fix my pull request.

My trouble is when running cargo test. I'm receiving a few panics. Is there a required setup prior to running cargo test for cli?

**Comment by karencfv** [comment]
Just saw the conversation in https://github.com/oxidecomputer/cli/pull/242 . I'm assuming you managed to get the tests running?
