### ISSUE TITLE
Make file argument mandatory to `ssh-key add`

### ISSUE THREAD

**Issue by plotnick** [oxidecomputer/cli-old#231]
In the name of convenience, we currently try to automatically guess the name of a public key in `~/.ssh/`. But this could be surprising, especially if multiple keys are available. So we shouldn't default this, but rather require an explicit file argument.

**Comment by plotnick** [comment]
Please chime in on this issue if you have feelings one way or another. :+1: (mandatory file arg) / :-1: (default to `~/.ssh/id_*.pub`) would be sufficient.

**Comment by bnaecker** [comment]
If we don't go this route, I'd like to at least recommend that we clearly document the default behavior. `oxide ssh-key add --help` does not describe anywhere what happens if run without any arguments.

**Comment by karencfv** [comment]
I believe requiring a specific file is the way to go. I like to avoid making any assumptions about our customers' set ups :)
