### ISSUE TITLE
`oxide auth login` should try to not die if it can't open a browser

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/cli-old#257]
Context: @iliana and I were going through a practice-run of some demo stuff, and we were using the CLI on `atrium`.

When running `oxide auth login`, I believe the CLI attempts to open a browser - when ssh'd into atrium, this fails, and returns an error.

However, it seems reasonable that we would want to use the CLI in configurations which are headless - shouldn't we print the URL, ask the user to access it, and poll for a response (as we normally do, when a browser is opened) until told otherwise?

What do y'all think?

**Comment by david-crespo** [comment]
This was attempted here: https://github.com/oxidecomputer/cli/pull/217

Guess it doesn't work!

**Comment by smklein** [comment]
Oh, interesting! I think this was attempted with the latest release (0.2.6), which was from June 29th. Looks like this went in right afterwards.

FYI @iliana  - auth should work if the CLI is built from source.
