### ISSUE TITLE
device auth flow

### ISSUE THREAD

**Issue by jessfraz** [oxidecomputer/cli-old#35]
this is a nice to have for the cli so that the flow is like:

```
oxide auth login

# user chooses to do interactively

cli gives a code

# browser opens to auth page and asks for code (can prepoulate as well)

# user logins w browser

# cli updates that it is logged in
```

https://oauth.net/2/device-flow/

this is in addition to using tokens, basically this returns to the cli a auth token

**Comment by plotnick** [comment]
Fixed by #188.
